#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Styling, testing and building your project before committing"

# Check Prettier standards
pnpm run check-format ||
(
    echo "Prettier Check Failed. Run pnpm run format, add changes and try commit again."
    false
)

# Check ESLint Standards
pnpm run check-lint ||
(
    echo "ESLint Check Failed. Make the required changes listed above, add changes and try to commit again."
    false
)

# Check tsconfig standards
pnpm run check-types ||
(
    echo "Type Check Failed. Make the changes required above."
    false
)

# If everything passes... Now we can commit
echo "All Checks Passed, Performing build check..."

pnpm run build ||
(
    echo "Next build failed: View the errors above to see why."
    false
)

# If everything passes... Now we can commit
echo "Committing..."
